### ISSUE TITLE
Renaming a path and swapping parameters breaks the parameter node in OAS 30

### ISSUE THREAD

**Issue by DyspC** [Apicurio/apicurio-data-models#251]
Hello, 

I was looking at how the RenamePathItemCommand_30 works to write its AaiChannel counterpart and I found this: 

If I swap parameters (for any reason) their renaming part does not handle the conflicts and leaves several parameters with the same name instead of swapping their names, thus undoing the command does not restore the original document.

An example of the resulting undo 
```yml
        parameters:
            -
                name: beerId
                schema:
                    type: string
                in: path
                required: true
            -
                name: beerId
                description: A unique identifier for a `Beer`.
                schema:
                    type: string
                in: path
                required: true
```

Here is a test suite, using 2 commands with an intermediate path makes the rename move parameters as expected but removing the temp path fails the test

[datamodels-testpete.zip](https://github.com/Apicurio/apicurio-data-models/files/6249588/datamodels-testpete.zip)
