### ISSUE TITLE
Why I'm getting "OAuth Flow is missing defined scopes" problem if scopes are optional in oauth2?

### ISSUE THREAD

**Issue by danielSenpaiDev** [Apicurio/apicurio-data-models#527]
Hi!
I'm using using Data Models to validate some API definitions. In any API with oauth2 authorization type I'm getting in the ValidationProblems list that issues found are "OAuth Flow is missing defined scopes", this one with medium severity.

For example, I have the following security schemes:

```
components:
    securitySchemes:
        application:
            flows:
                clientCredentials:
                    tokenUrl: 'https://myserver.com/login/v2/authorization'
                    scopes: {}
```

But this should be valid, however the validation returns that is not. I'm using the Apicurio Data Models library version 1.1.26 on Java, as far as I'm aware, 1.1.26 is compliant with OAS 3.0.2. 

I'm using this code (I'm using the deprecated method because I couldn't find usage documentation about the new one):
```
        Document api = null;
        List<ValidationProblem> problems = null;
        // There is no documentation about the new validateDocument method. So, I'm forced to use the deprecated one.
        try {
            api = Library.readDocumentFromJSONString(contract);
            problems = Library.validate(api, null);    
        } catch (Exception e) {
            log.error("Error analizing OAS3 validation", e);
            return false;
        }
```
the "problems" object comes with an element with the message "OAuth Flow is missing defined scopes" described.

So I need your help guys, anyone can help me if this is ok, please? or it's an issue? or I'm doing something wrong?

Thanks in advance.
