### ISSUE TITLE
OAS v3.1 schema removes `nullable` and uses array for `type`

### ISSUE THREAD

**Issue by MikeEdgar** [Apicurio/apicurio-data-models#612]
Source: [1]

```yaml
# OpenAPI v3.0
type: string
nullable: true
```

```yaml
# OpenAPI v3.1
type:
- "string"
- "null" 
```

[1] https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0
